sonar.projectKey=3cfe0db651832242e234c7b38fc6febbcc58d0b9
sonar.organization=csontikka
sonar.sources=custom_components/syncthing_extended
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
